# Generated by Django 2.2.5 on 2019-12-09 18:46

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_deliverylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylocation',
            name='pin_code',
            field=models.IntegerField(validators=[user_auth.models.pin_code_validation]),
        ),
    ]
