# Generated by Django 2.2.5 on 2019-12-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20191209_1558'),
        ('user_auth', '0007_auto_20191209_1846'),
    ]

    operations = [
    ]
