# Generated by Django 2.2.5 on 2019-12-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_merge_20191210_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='location',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
