# Generated by Django 2.2.5 on 2019-12-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_auto_20191212_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_type',
            field=models.CharField(choices=[('Tournaments', 'Tournaments'), ('Products', 'Products'), ('Bidding', 'Bidding')], max_length=150),
        ),
    ]
