# Generated by Django 2.2.5 on 2019-12-12 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0011_auto_20191212_0752'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='services',
            unique_together={('user_name', 'service_type')},
        ),
    ]
