# Generated by Django 2.2.5 on 2019-12-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_auto_20191212_0820'),
        ('user_auth', '0009_deliverylocation_location'),
    ]

    operations = [
    ]
