# Generated by Django 2.2.5 on 2019-12-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_merge_20191212_1449'),
        ('user_auth', '0013_merge_20191212_1735'),
    ]

    operations = [
    ]
