# Generated by Django 2.2.5 on 2019-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_auto_20191111_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_info',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sport_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/sports/sport-image'),
        ),
        migrations.AddField(
            model_name='sport_info',
            name='playlist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
