# Generated by Django 2.2.5 on 2019-11-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_auto_20191116_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport_info',
            name='icon',
        ),
    ]
