# Generated by Django 2.2.5 on 2019-11-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0020_auto_20191116_1156'),
        ('sports', '0018_sport_info_playlist'),
    ]

    operations = [
    ]
