# Generated by Django 2.2.5 on 2019-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
