# Generated by Django 2.2.5 on 2019-12-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
