# Generated by Django 2.2.5 on 2019-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20191109_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weigth',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
