# Generated by Django 2.2.5 on 2019-12-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_deliveryoptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weigth',
            new_name='weight',
        ),
    ]
