# Generated by Django 2.2.5 on 2019-12-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20191204_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliveryoptions',
            unique_together={('product', 'name_id')},
        ),
    ]
