# Generated by Django 2.2.5 on 2019-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20191204_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='location',
            field=models.CharField(default='delhi', max_length=150),
            preserve_default=False,
        ),
    ]
