# Generated by Django 2.2.5 on 2019-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20191205_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='pincode',
            field=models.PositiveIntegerField(default=533006),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='deliveryoptions',
            name='location',
        ),
    ]
