# Generated by Django 2.2.5 on 2019-12-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20191209_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='location',
            field=models.CharField(default='kakinada', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='deliveryoptions',
            name='pincode',
        ),
        migrations.AlterUniqueTogether(
            name='deliveryoptions',
            unique_together={('name_id', 'product', 'location')},
        ),
    ]
