# Generated by Django 2.2.5 on 2019-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20191209_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='location',
            field=models.CharField(default='kakinada', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='deliveryoptions',
            name='pincode',
        ),
    ]
